apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
  # Service name
  name: docker-app-svc
spec:
  selector:
    # Selector for Pods
    app: docker-app
  ports:
    # Port Map
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer